"""adilet's change does not applied

Revision ID: 058431ec1ac9
Revises: 9a6f4e2ffa3a
Create Date: 2026-04-04 20:43:17.209048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058431ec1ac9'
down_revision: Union[str, Sequence[str], None] = '9a6f4e2ffa3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('last_read_message_id', sa.Integer(), nullable=True))
    op.add_column('chat_members', sa.Column('trip_removal_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'chat_members', 'messages', ['last_read_message_id'], ['id'], ondelete='SET NULL')
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('offers', sa.Column('offerer_outcome_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'offerer_outcome_seen_at')
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_column('chat_members', 'trip_removal_seen_at')
    op.drop_column('chat_members', 'last_read_message_id')
    # ### end Alembic commands ###
